repos:
  # General-purpose hooks for all projects
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use a specific, stable version
    hooks:
      - id: trailing-whitespace
        name: Trim Trailing Whitespace
        description: Removes trailing whitespace from files.
      - id: end-of-file-fixer
        name: Fix End of Files
        description: Ensures files end with a newline.
      - id: check-yaml
        name: Check YAML
        description: Validates YAML files for syntax errors.
      - id: check-added-large-files
        name: Check for Large Files
        description: Prevents committing files larger than 500KB.
        args: ['--maxkb=500']

  # Java/Maven-specific hooks for code quality and checks
  - repo: https://github.com/ejba/pre-commit-maven
    rev: v0.3.3  # Use a specific, stable version
    hooks:
      - id: maven
        name: Maven Compile
        description: Runs 'mvn clean compile' to ensure the project compiles.
        args: ['clean', 'compile']
        language: system
        pass_filenames: false
      - id: maven
        name: Maven Test
        description: Runs 'mvn test' to execute unit tests.
        args: ['test']
        language: system
        pass_filenames: false
      - id: maven
        name: Run Checkstyle
        description: Runs 'mvn checkstyle:check' to enforce coding standards.
        args: ['checkstyle:check']
        language: system
        pass_filenames: false
      - id: maven
        name: Apply Spotless
        description: Runs 'mvn spotless:apply' to format code.
        args: ['spotless:apply']
        language: system
        pass_filenames: false
